spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST_WRITER:database-1.cluster-c4dwogyamid9.us-east-1.rds.amazonaws.com}:5432/${DB_NAME:postgres}?sslmode=require
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:5}
      connection-timeout: ${DB_POOL_TIMEOUT_MS:30000}
  jpa:
    hibernate:
      ddl-auto: validate

aws:
  dynamodb-local:
    enabled: false

  s3:
    endpoint: https://s3.amazonaws.com  # AWS real
