spring:
  config:
    activate:
      on-profile: dev

aws:
  dynamodb-local:
    enabled: true

  s3:
    endpoint: http://localhost:4566  # LocalStack

app:
  cors:
    dev-allowed-origins:
      - http://localhost:5173
      - https://localhost:5173
